import { describe, expect, it } from "vitest";

import { HULL, STATIONS } from "../model/boat.ts";
import type { Vec2 } from "../model/units.ts";
import {
  cubicPoint,
  HULL_OUTLINE,
  hullPathData,
  outlineRadius,
  type CubicSegment,
} from "./hull.ts";

/** Metres. A tenth of a millimetre on a nineteen-foot boat is exactness enough. */
const PRECISION = 4;

/** Sample count for sweeping a segment. Fine enough to catch any bulge or waist. */
const SAMPLES = 400;

/** Every sampled point of the starboard half, bow to transom corner. */
function starboardPoints(): Vec2[] {
  const points: Vec2[] = [HULL_OUTLINE.bow];
  let start = HULL_OUTLINE.bow;
  for (const segment of HULL_OUTLINE.starboard) {
    for (let i = 1; i <= SAMPLES; i += 1) {
      points.push(cubicPoint(start, segment, i / SAMPLES));
    }
    start = segment.end;
  }
  return points;
}

/** Half-beam at a station, as a fraction of LOA aft of the bow. Linear scan; exact enough. */
function halfBeamAt(fractionAft: number): number {
  const y = STATIONS.bow.y + fractionAft * HULL.loa;
  let nearest = starboardPoints()[0]!;
  for (const point of starboardPoints()) {
    if (Math.abs(point.y - y) < Math.abs(nearest.y - y)) nearest = point;
  }
  return nearest.x;
}

describe("hull outline (DESIGN.md §4.1)", () => {
  it("spans exactly the boat's length, bow to transom", () => {
    const points = starboardPoints();
    const ys = points.map((p) => p.y);
    expect(Math.min(...ys)).toBeCloseTo(STATIONS.bow.y, PRECISION);
    expect(Math.max(...ys)).toBeCloseTo(STATIONS.stern.y, PRECISION);
    expect(Math.max(...ys) - Math.min(...ys)).toBeCloseTo(HULL.loa, PRECISION);
  });

  it("reaches exactly the boat's beam and never exceeds it", () => {
    const widest = Math.max(...starboardPoints().map((p) => p.x));
    // Not approximately: the widest point's handles are both at the half beam,
    // so the tangent there is fore-and-aft and the maximum is the endpoint.
    expect(widest).toBeCloseTo(HULL.beam / 2, PRECISION);
    expect(widest).toBeLessThanOrEqual(HULL.beam / 2);
  });

  it("keeps the abstract 7:19 proportion the design asks for", () => {
    // Checked against the boat's own figures, not the literal 7/19 — LOA is
    // 19'2", so the true ratio is 7 : 19.167, which is 0.9% off the sketch.
    // §4.1's "≈ 7:19" is the sketch; boat.ts is the spec.
    expect(HULL.loa / HULL.beam).toBeCloseTo((19 + 2 / 12) / 7, 4);
    expect(HULL.loa / HULL.beam).toBeCloseTo(19 / 7, 1);
  });

  it("widens monotonically to the maximum beam, then narrows to the transom", () => {
    const [forward, aft] = HULL_OUTLINE.starboard;
    const widening = sweepX(HULL_OUTLINE.bow, forward);
    const narrowing = sweepX(HULL_OUTLINE.maxBeam, aft);
    expect(isMonotonic(widening, "up")).toBe(true);
    expect(isMonotonic(narrowing, "down")).toBe(true);
  });

  it("is symmetric about the centreline", () => {
    // The port half is generated by mirroring rather than written down, so this
    // asserts the generator: every `C` in the path data has a negated twin.
    const xs = pathNumbers(hullPathData())
      .filter((_, index) => index % 2 === 0)
      .map((x) => Number(x.toFixed(PRECISION)));
    const negated = xs.map((x) => (x === 0 ? 0 : -x));
    expect(new Set(xs)).toEqual(new Set(negated));
  });

  it("puts the boat's shoulders where a keelboat has them", () => {
    // The shape's review surface: half-beam as a fraction of maximum beam, at
    // quarter stations aft of the bow. Numbers rather than "does it look like a
    // boat" — refair the hull and this table is what you re-read.
    const halfBeam = HULL.beam / 2;
    expect(halfBeamAt(0.1) / halfBeam).toBeCloseTo(0.34, 1); // a stem, not a needle
    expect(halfBeamAt(0.25) / halfBeam).toBeCloseTo(0.74, 1);
    expect(halfBeamAt(0.5) / halfBeam).toBeCloseTo(1.0, 1); // widest just abaft midships
    expect(halfBeamAt(0.75) / halfBeam).toBeCloseTo(0.91, 1); // beam carried aft
    expect(halfBeamAt(0.9) / halfBeam).toBeCloseTo(0.72, 1);
    // The transom is narrow, but it is not a point.
    expect(HULL_OUTLINE.transomCorner.x / halfBeam).toBeCloseTo(0.48, 2);
  });

  it("meets the transom at a corner rather than tangentially", () => {
    const [, aft] = HULL_OUTLINE.starboard;
    expect(aft.control2.y).toBeLessThan(HULL_OUTLINE.transomCorner.y);
  });
});

describe("hull extent", () => {
  it("is set by the transom corners, not by the stern station", () => {
    const corner = Math.hypot(HULL_OUTLINE.transomCorner.x, HULL_OUTLINE.transomCorner.y);
    expect(outlineRadius()).toBeCloseTo(corner, 3);
    // The point of measuring rather than declaring: the corner is further out
    // than anything boat.ts names.
    expect(outlineRadius()).toBeGreaterThan(Math.abs(STATIONS.stern.y));
  });

  it("contains every sampled point of the outline", () => {
    const radius = outlineRadius();
    for (const point of starboardPoints()) {
      expect(Math.hypot(point.x, point.y)).toBeLessThanOrEqual(radius + 1e-9);
    }
  });
});

describe("hull path data", () => {
  it("is a closed path that starts at the bow", () => {
    const d = hullPathData();
    expect(d.startsWith("M 0 -2.1336")).toBe(true);
    expect(d.endsWith("Z")).toBe(true);
  });

  it("emits nothing a renderer would choke on", () => {
    const d = hullPathData();
    expect(d).not.toMatch(/NaN|Infinity|e[+-]/i);
    expect(d).not.toMatch(/(^|\s)-0(\s|$)/);
    for (const value of pathNumbers(d)) {
      expect(Number.isFinite(value)).toBe(true);
    }
  });
});

// --- helpers ---------------------------------------------------------------

function sweepX(start: Vec2, segment: CubicSegment): number[] {
  return Array.from({ length: SAMPLES + 1 }, (_, i) => cubicPoint(start, segment, i / SAMPLES).x);
}

function isMonotonic(values: number[], direction: "up" | "down"): boolean {
  const sign = direction === "up" ? 1 : -1;
  return values.every((value, i) => i === 0 || sign * (value - values[i - 1]!) >= -1e-12);
}

function pathNumbers(d: string): number[] {
  return (d.match(/-?\d+(\.\d+)?/g) ?? []).map(Number);
}
